import { CarDetail } from './carTypes';

export const cars: CarDetail[] = [
  {
    id: '1',
    announcementTitle: 'Toyota Corolla 2.0 XEi 2022',
    price: 145000.0,
    status: 'Disponível',
    principalImageUrl: 'https://example.com/images/corolla.jpg',
    gallery: [
      { url: 'https://example.com/images/corolla.jpg', isPrincipal: true, legend: 'Frente' },
      {
        url: 'https://example.com/images/corolla_interior.jpg',
        isPrincipal: false,
        legend: 'Interior',
      },
      {
        url: 'https://example.com/images/corolla_traseira.jpg',
        isPrincipal: false,
        legend: 'Traseira',
      },
    ],
    specifications: {
      brand: 'Toyota',
      model: 'Corolla',
      yearManufacture: 2021,
      yearModel: 2022,
      mileage: 15000,
      fuel: 'Flex',
      transmission: 'CVT',
      power: '177 cv',
      color: 'Prata',
      doors: 4,
      bodyType: 'Sedan',
      engine: '2.0',
      plateEnd: 1,
    },
    standardItems: [
      { name: 'Ar condicionado digital', category: 'Conforto' },
      { name: 'Direção elétrica', category: 'Conforto' },
      { name: '7 Airbags', category: 'Segurança' },
      { name: 'Controle de estabilidade', category: 'Segurança' },
      { name: 'Central multimídia', category: 'Tecnologia' },
    ],
    optionalItems: [
      { name: 'Teto solar', category: 'Estética' },
      { name: 'Bancos de couro', category: 'Conforto' },
    ],
    history: {
      origin: 'Concessionária',
      previousOwners: 1,
      warranty: 'Até 12/2024',
      revisions: [
        { date: '2022-12-15T00:00:00.000Z', mileage: 10000, location: 'Concessionária Toyota' },
      ],
      technicalReport: { inspectionDate: '2023-11-20T00:00:00.000Z', result: 'Aprovado' },
    },
    salesConditions: {
      paymentMethods: ['À vista', 'Financiamento'],
      acceptsTrade: true,
      financing: { minEntry: 20, interestRate: 1.5, maxInstallments: 48 },
      requiredDocuments: ['CNH', 'Comprovante de Residência', 'Comprovante de Renda'],
      documentalSituation: { status: 'Regular' },
    },
  },
  {
    id: '2',
    announcementTitle: 'Honda Civic 2.0 Sport 2021',
    price: 138000.0,
    status: 'Disponível',
    principalImageUrl: 'https://example.com/images/civic.jpg',
    gallery: [
      { url: 'https://example.com/images/civic.jpg', isPrincipal: true, legend: 'Frente' },
      {
        url: 'https://example.com/images/civic_interior.jpg',
        isPrincipal: false,
        legend: 'Interior',
      },
    ],
    specifications: {
      brand: 'Honda',
      model: 'Civic',
      yearManufacture: 2021,
      yearModel: 2021,
      mileage: 22000,
      fuel: 'Flex',
      transmission: 'CVT',
      power: '155 cv',
      color: 'Branco',
      doors: 4,
      bodyType: 'Sedan',
      engine: '2.0',
      plateEnd: 2,
    },
    standardItems: [
      { name: 'Ar condicionado', category: 'Conforto' },
      { name: 'Direção elétrica', category: 'Conforto' },
      { name: '6 Airbags', category: 'Segurança' },
      { name: 'Freios ABS', category: 'Segurança' },
    ],
    optionalItems: [],
    history: {
      origin: 'Particular',
      previousOwners: 1,
      revisions: [
        { date: '2022-05-10T00:00:00.000Z', mileage: 10500, location: 'Oficina Especializada' },
      ],
      claims: [
        {
          date: '2023-01-20T00:00:00.000Z',
          type: 'Pequena colisão',
          description: 'Reparo no para-choque dianteiro.',
        },
      ],
      technicalReport: {
        inspectionDate: '2023-01-15T00:00:00.000Z',
        result: 'Aprovado com ressalvas',
      },
    },
    salesConditions: {
      paymentMethods: ['À vista', 'Financiamento', 'Consórcio'],
      acceptsTrade: true,
      financing: { minEntry: 30, interestRate: 1.8, maxInstallments: 36 },
      requiredDocuments: ['CNH', 'Comprovante de Residência'],
      documentalSituation: { status: 'Regular' },
    },
  },
  {
    id: '3',
    announcementTitle: 'Chevrolet Onix 1.0 Turbo Premier 2023',
    price: 85000.0,
    status: 'Reservado',
    principalImageUrl: 'https://example.com/images/onix.jpg',
    gallery: [{ url: 'https://example.com/images/onix.jpg', isPrincipal: true }],
    specifications: {
      brand: 'Chevrolet',
      model: 'Onix',
      yearManufacture: 2022,
      yearModel: 2023,
      mileage: 5000,
      fuel: 'Flex',
      transmission: 'Automático',
      power: '116 cv',
      color: 'Azul',
      doors: 4,
      bodyType: 'Hatch',
      engine: '1.0',
      plateEnd: 3,
    },
    standardItems: [
      { name: 'Easy Park', category: 'Tecnologia' },
      { name: 'Wi-Fi Nativo', category: 'Tecnologia' },
      { name: 'Alerta de ponto cego', category: 'Segurança' },
    ],
    optionalItems: [],
    history: { origin: 'Concessionária', previousOwners: 0 },
    salesConditions: {
      paymentMethods: ['À vista', 'Financiamento'],
      acceptsTrade: false,
      requiredDocuments: ['CNH', 'Comprovante de Residência', 'Comprovante de Renda'],
      documentalSituation: { status: 'Regular' },
    },
  },
  {
    id: '4',
    announcementTitle: 'Hyundai HB20 1.0 Diamond 2022',
    price: 82000.0,
    status: 'Disponível',
    principalImageUrl: 'https://example.com/images/hb20.jpg',
    gallery: [{ url: 'https://example.com/images/hb20.jpg', isPrincipal: true }],
    specifications: {
      brand: 'Hyundai',
      model: 'HB20',
      yearManufacture: 2022,
      yearModel: 2022,
      mileage: 12000,
      fuel: 'Flex',
      transmission: 'Automático',
      power: '120 cv',
      color: 'Vermelho',
      doors: 4,
      bodyType: 'Hatch',
      engine: '1.0',
      plateEnd: 4,
    },
    standardItems: [
      { name: 'Frenagem autônoma de emergência', category: 'Segurança' },
      { name: 'Assistente de permanência em faixa', category: 'Segurança' },
    ],
    optionalItems: [],
    history: { origin: 'Particular', previousOwners: 1 },
    salesConditions: {
      paymentMethods: ['À vista', 'Financiamento'],
      acceptsTrade: true,
      requiredDocuments: ['CNH', 'Comprovante de Residência'],
      documentalSituation: { status: 'Regular' },
    },
  },
  {
    id: '5',
    announcementTitle: 'Renault Kwid 1.0 Intense 2020',
    price: 55000.0,
    status: 'Vendido',
    principalImageUrl: 'https://example.com/images/kwid.jpg',
    gallery: [{ url: 'https://example.com/images/kwid.jpg', isPrincipal: true }],
    specifications: {
      brand: 'Renault',
      model: 'Kwid',
      yearManufacture: 2020,
      yearModel: 2020,
      mileage: 45000,
      fuel: 'Flex',
      transmission: 'Manual',
      power: '70 cv',
      color: 'Laranja',
      doors: 4,
      bodyType: 'Hatch',
      engine: '1.0',
      plateEnd: 5,
    },
    standardItems: [
      { name: 'Ar condicionado', category: 'Conforto' },
      { name: 'Direção elétrica', category: 'Conforto' },
    ],
    optionalItems: [],
    history: { origin: 'Locadora', previousOwners: 1 },
    salesConditions: {
      paymentMethods: ['À vista'],
      acceptsTrade: false,
      requiredDocuments: ['CNH', 'Comprovante de Residência'],
      documentalSituation: { status: 'Pendente', pendingIssues: ['Multa não paga'] },
    },
  },
  {
    id: '6',
    announcementTitle: 'Fiat Mobi 1.0 Like 2021',
    price: 60000.0,
    status: 'Disponível',
    principalImageUrl: 'https://example.com/images/mobi.jpg',
    gallery: [{ url: 'https://example.com/images/mobi.jpg', isPrincipal: true }],
    specifications: {
      brand: 'Fiat',
      model: 'Mobi',
      yearManufacture: 2021,
      yearModel: 2021,
      mileage: 30000,
      fuel: 'Flex',
      transmission: 'Manual',
      power: '75 cv',
      color: 'Preto',
      doors: 4,
      bodyType: 'Hatch',
      engine: '1.0',
      plateEnd: 6,
    },
    standardItems: [
      { name: 'Ar condicionado', category: 'Conforto' },
      { name: 'Vidros elétricos dianteiros', category: 'Conforto' },
    ],
    optionalItems: [],
    history: { origin: 'Particular', previousOwners: 1 },
    salesConditions: {
      paymentMethods: ['À vista', 'Financiamento'],
      acceptsTrade: true,
      requiredDocuments: ['CNH', 'Comprovante de Residência'],
      documentalSituation: { status: 'Regular' },
    },
  },
  {
    id: '7',
    announcementTitle: 'Jeep Compass Longitude 1.3 Turbo 2022',
    price: 180000.0,
    status: 'Disponível',
    principalImageUrl: 'https://example.com/images/compass.jpg',
    gallery: [
      { url: 'https://example.com/images/compass.jpg', isPrincipal: true, legend: 'Frente' },
      {
        url: 'https://example.com/images/compass_interior.jpg',
        isPrincipal: false,
        legend: 'Painel',
      },
      {
        url: 'https://example.com/images/compass_lateral.jpg',
        isPrincipal: false,
        legend: 'Lateral',
      },
    ],
    specifications: {
      brand: 'Jeep',
      model: 'Compass',
      yearManufacture: 2022,
      yearModel: 2022,
      mileage: 18000,
      fuel: 'Flex',
      transmission: 'Automático',
      power: '185 cv',
      color: 'Cinza',
      doors: 4,
      bodyType: 'SUV',
      engine: '1.3',
      plateEnd: 7,
    },
    standardItems: [
      { name: 'Ar condicionado dual zone', category: 'Conforto' },
      { name: 'Bancos de couro', category: 'Conforto' },
      { name: 'Controle de tração 4x2', category: 'Segurança' },
      { name: 'Faróis Full LED', category: 'Estética' },
      { name: 'Painel de instrumentos digital', category: 'Tecnologia' },
    ],
    optionalItems: [
      { name: 'Teto solar panorâmico', category: 'Estética' },
      { name: 'Pacote de som premium Beats', category: 'Tecnologia' },
    ],
    history: {
      origin: 'Concessionária',
      previousOwners: 0,
      warranty: 'Até 08/2025',
      revisions: [
        { date: '2023-08-01T00:00:00.000Z', mileage: 12000, location: 'Concessionária Jeep' },
      ],
      technicalReport: { inspectionDate: '2022-08-01T00:00:00.000Z', result: 'Aprovado' },
    },
    salesConditions: {
      paymentMethods: ['À vista', 'Financiamento', 'Leasing'],
      acceptsTrade: false,
      financing: { minEntry: 25, interestRate: 1.4, maxInstallments: 60 },
      requiredDocuments: ['CNH', 'Comprovante de Residência', 'Comprovante de Renda'],
      documentalSituation: { status: 'Regular' },
    },
  },
  {
    id: '8',
    announcementTitle: 'Jeep Renegade 1.8 Longitude 2021',
    price: 130000.0,
    status: 'Disponível',
    principalImageUrl: 'https://example.com/images/renegade.jpg',
    gallery: [{ url: 'https://example.com/images/renegade.jpg', isPrincipal: true }],
    specifications: {
      brand: 'Jeep',
      model: 'Renegade',
      yearManufacture: 2021,
      yearModel: 2021,
      mileage: 25000,
      fuel: 'Flex',
      transmission: 'Automático',
      power: '139 cv',
      color: 'Verde',
      doors: 4,
      bodyType: 'SUV',
      engine: '1.8',
      plateEnd: 8,
    },
    standardItems: [
      { name: 'Ar condicionado', category: 'Conforto' },
      { name: 'Central multimídia', category: 'Tecnologia' },
    ],
    optionalItems: [],
    history: { origin: 'Particular', previousOwners: 1 },
    salesConditions: {
      paymentMethods: ['À vista', 'Financiamento'],
      acceptsTrade: true,
      requiredDocuments: ['CNH', 'Comprovante de Residência'],
      documentalSituation: { status: 'Regular' },
    },
  },
  {
    id: '9',
    announcementTitle: 'Hyundai Creta 1.0 Platinum 2023',
    price: 135000.0,
    status: 'Disponível',
    principalImageUrl: 'https://example.com/images/creta.jpg',
    gallery: [{ url: 'https://example.com/images/creta.jpg', isPrincipal: true }],
    specifications: {
      brand: 'Hyundai',
      model: 'Creta',
      yearManufacture: 2022,
      yearModel: 2023,
      mileage: 8000,
      fuel: 'Flex',
      transmission: 'Automático',
      power: '120 cv',
      color: 'Prata',
      doors: 4,
      bodyType: 'SUV',
      engine: '1.0',
      plateEnd: 9,
    },
    standardItems: [
      { name: 'Teto solar panorâmico', category: 'Estética' },
      { name: 'Câmera 360º', category: 'Tecnologia' },
    ],
    optionalItems: [],
    history: { origin: 'Concessionária', previousOwners: 0 },
    salesConditions: {
      paymentMethods: ['À vista', 'Financiamento'],
      acceptsTrade: true,
      requiredDocuments: ['CNH', 'Comprovante de Residência', 'Comprovante de Renda'],
      documentalSituation: { status: 'Regular' },
    },
  },
  {
    id: '10',
    announcementTitle: 'Volkswagen T-Cross 1.4 Highline 2022',
    price: 140000.0,
    status: 'Disponível',
    principalImageUrl: 'https://example.com/images/tcross.jpg',
    gallery: [{ url: 'https://example.com/images/tcross.jpg', isPrincipal: true }],
    specifications: {
      brand: 'Volkswagen',
      model: 'T-Cross',
      yearManufacture: 2022,
      yearModel: 2022,
      mileage: 14000,
      fuel: 'Flex',
      transmission: 'Automático',
      power: '150 cv',
      color: 'Branco',
      doors: 4,
      bodyType: 'SUV',
      engine: '1.4',
      plateEnd: 0,
    },
    standardItems: [
      { name: 'Painel digital', category: 'Tecnologia' },
      { name: 'ACC', category: 'Segurança' },
    ],
    optionalItems: [],
    history: { origin: 'Particular', previousOwners: 1 },
    salesConditions: {
      paymentMethods: ['À vista', 'Financiamento'],
      acceptsTrade: true,
      requiredDocuments: ['CNH', 'Comprovante de Residência'],
      documentalSituation: { status: 'Regular' },
    },
  },
  {
    id: '11',
    announcementTitle: 'Volkswagen Gol 1.6 MSI 2019',
    price: 48000.0,
    status: 'Disponível',
    principalImageUrl: 'https://example.com/images/gol.jpg',
    gallery: [{ url: 'https://example.com/images/gol.jpg', isPrincipal: true }],
    specifications: {
      brand: 'Volkswagen',
      model: 'Gol',
      yearManufacture: 2019,
      yearModel: 2019,
      mileage: 60000,
      fuel: 'Flex',
      transmission: 'Manual',
      power: '104 cv',
      color: 'Prata',
      doors: 4,
      bodyType: 'Hatch',
      engine: '1.6',
      plateEnd: 1,
    },
    standardItems: [
      { name: 'Ar condicionado', category: 'Conforto' },
      { name: 'Direção hidráulica', category: 'Conforto' },
    ],
    optionalItems: [],
    history: { origin: 'Particular', previousOwners: 2 },
    salesConditions: {
      paymentMethods: ['À vista', 'Financiamento'],
      acceptsTrade: true,
      requiredDocuments: ['CNH', 'Comprovante de Residência'],
      documentalSituation: { status: 'Regular' },
    },
  },
  {
    id: '12',
    announcementTitle: 'Fiat Argo 1.3 Drive 2022',
    price: 78000.0,
    status: 'Disponível',
    principalImageUrl: 'https://example.com/images/argo.jpg',
    gallery: [{ url: 'https://example.com/images/argo.jpg', isPrincipal: true }],
    specifications: {
      brand: 'Fiat',
      model: 'Argo',
      yearManufacture: 2022,
      yearModel: 2022,
      mileage: 19000,
      fuel: 'Flex',
      transmission: 'Manual',
      power: '109 cv',
      color: 'Cinza',
      doors: 4,
      bodyType: 'Hatch',
      engine: '1.3',
      plateEnd: 2,
    },
    standardItems: [
      { name: 'Central multimídia', category: 'Tecnologia' },
      { name: 'Controle de estabilidade', category: 'Segurança' },
    ],
    optionalItems: [],
    history: { origin: 'Concessionária', previousOwners: 1 },
    salesConditions: {
      paymentMethods: ['À vista', 'Financiamento'],
      acceptsTrade: true,
      requiredDocuments: ['CNH', 'Comprovante de Residência'],
      documentalSituation: { status: 'Regular' },
    },
  },
  {
    id: '13',
    announcementTitle: 'Toyota Yaris 1.5 XLS 2021',
    price: 95000.0,
    status: 'Disponível',
    principalImageUrl: 'https://example.com/images/yaris.jpg',
    gallery: [{ url: 'https://example.com/images/yaris.jpg', isPrincipal: true }],
    specifications: {
      brand: 'Toyota',
      model: 'Yaris',
      yearManufacture: 2021,
      yearModel: 2021,
      mileage: 28000,
      fuel: 'Flex',
      transmission: 'CVT',
      power: '110 cv',
      color: 'Azul',
      doors: 4,
      bodyType: 'Hatch',
      engine: '1.5',
      plateEnd: 3,
    },
    standardItems: [
      { name: 'Teto solar', category: 'Estética' },
      { name: '7 Airbags', category: 'Segurança' },
    ],
    optionalItems: [],
    history: { origin: 'Particular', previousOwners: 1 },
    salesConditions: {
      paymentMethods: ['À vista', 'Financiamento'],
      acceptsTrade: true,
      requiredDocuments: ['CNH', 'Comprovante de Residência'],
      documentalSituation: { status: 'Regular' },
    },
  },
  {
    id: '14',
    announcementTitle: 'Honda Fit 1.5 EXL 2020',
    price: 90000.0,
    status: 'Disponível',
    principalImageUrl: 'https://example.com/images/fit.jpg',
    gallery: [{ url: 'https://example.com/images/fit.jpg', isPrincipal: true }],
    specifications: {
      brand: 'Honda',
      model: 'Fit',
      yearManufacture: 2020,
      yearModel: 2020,
      mileage: 35000,
      fuel: 'Flex',
      transmission: 'CVT',
      power: '116 cv',
      color: 'Branco',
      doors: 4,
      bodyType: 'Hatch',
      engine: '1.5',
      plateEnd: 4,
    },
    standardItems: [
      { name: 'Bancos de couro', category: 'Conforto' },
      { name: 'Magic Seat', category: 'Conforto' },
    ],
    optionalItems: [],
    history: { origin: 'Particular', previousOwners: 1 },
    salesConditions: {
      paymentMethods: ['À vista', 'Financiamento'],
      acceptsTrade: true,
      requiredDocuments: ['CNH', 'Comprovante de Residência'],
      documentalSituation: { status: 'Regular' },
    },
  },
  {
    id: '15',
    announcementTitle: 'Chevrolet Tracker 1.2 Turbo Premier 2022',
    price: 130000.0,
    status: 'Disponível',
    principalImageUrl: 'https://example.com/images/tracker.jpg',
    gallery: [{ url: 'https://example.com/images/tracker.jpg', isPrincipal: true }],
    specifications: {
      brand: 'Chevrolet',
      model: 'Tracker',
      yearManufacture: 2022,
      yearModel: 2022,
      mileage: 21000,
      fuel: 'Flex',
      transmission: 'Automático',
      power: '133 cv',
      color: 'Preto',
      doors: 4,
      bodyType: 'SUV',
      engine: '1.2',
      plateEnd: 5,
    },
    standardItems: [
      { name: 'Teto solar panorâmico', category: 'Estética' },
      { name: 'Alerta de colisão frontal', category: 'Segurança' },
    ],
    optionalItems: [],
    history: { origin: 'Concessionária', previousOwners: 1 },
    salesConditions: {
      paymentMethods: ['À vista', 'Financiamento'],
      acceptsTrade: true,
      requiredDocuments: ['CNH', 'Comprovante de Residência'],
      documentalSituation: { status: 'Regular' },
    },
  },
];
